{
 "title": "crcdashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "VM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "crc vm"
    }
   ]
  },
  {
   "title": "Memory used",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Number of queries with status 2xx",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "irate(http_requests_total{handler=\"/api/v1/applications/{id}\", method=\"GET\", status=\"2xx\"}[1m])",
     "legendFormat": "Queries"
    }
   ]
  },
  {
   "title": "Number of queries with status 5xx",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 9 },
   "targets": [
    {
     "expr": "irate(http_requests_total{handler=\"/api/v1/applications/{id}\",method=\"GET\",status=\"5xx\"}[1m])",
     "legendFormat": "Queries"
    }
   ]
  },
  {
   "title": "Queries 5xx per all",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 9 },
   "targets": [
    {
     "expr": "irate(http_requests_total{handler=\"/api/v1/applications/{id}\", method=\"GET\", status=\"5xx\"}[1m])",
     "legendFormat": "status 5xx"
    },
    {
     "expr": "sum(irate(http_requests_total[1m]))",
     "legendFormat": "all queries"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum (irate(http_requests_total{handler=\"/api/v1/applications/{id}\", method=\"GET\", status=\"5xx\"}[1m]))\r\n  / ignoring(statusCode) group_left\r\nsum (irate(http_requests_total[1m]))) * 100",
     "legendFormat": "Error rate queries"
    }
   ]
  },
  {
   "title": "Average request time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(sum(irate(http_request_duration_seconds_sum[1m]))   \r\n/ ignoring(statusCode) group_left \r\nsum(irate(http_requests_total[1m]))) * 1000",
     "legendFormat": "Request time"
    }
   ]
  },
  {
   "title": "Correct response rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum (sum_over_time(http_requests_total{handler=\"/api/v1/applications/{id}\", method=\"GET\", status!=\"5xx\"}[1h]))\r\n  / ignoring(statusCode) group_left\r\nsum (sum_over_time(http_requests_total[1h]))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queries shorter then 500ms",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum (sum_over_time(http_request_duration_highr_seconds_bucket{le=\"0.5\"}[1h]))\r\n  / ignoring(statusCode) group_left\r\nsum (sum_over_time(http_requests_total[1h]))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pg_settings_max_connections", "legendFormat": "__auto" }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Transactions rollback",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum(irate(pg_stat_database_xact_rollback[1m]))",
     "legendFormat": "Transactions"
    }
   ]
  },
  {
   "title": "Active transactions",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 28 },
   "targets": [
    { "expr": "sum(pg_stat_activity_count)", "legendFormat": "Transactions" }
   ]
  }
 ]
}